language: node_js

branches:
  only:
    - master
    
addons:
  sonarcloud:
    organization: "sakamotto-github"
    token:
      secure: a48e3dff64de99d176e281a1f6fbdacab3c9be3c
script:
  # other script steps might be done before running the actual analysis
  #- build-wrapper-linux-x86-64 --out-dir outDir make all
  - cd loja-virtual-app/src/app
  - sonar-scanner
  - echo "Hello..."
    
#script:
    #- sonar-scanner.bat -Dsonar.projectKey=TrabalhoIntegradoKey -Dsonar.organization=sakamotto-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a48e3dff64de99d176e281a1f6fbdacab3c9be3c
#    - echo "Hello..."
